### ISSUE TITLE
Unexpected behavior with `psum`, `pmean`, and `pprod`

### ISSUE THREAD

**Issue by Kamgang-B** [2005m/kit#17]
Hi, Thank you for this very useful package.
I was working on a (class) project using some functions in the `kit` package (`psum`, `pprop` and `pmean`) and they showed some unexpected behavior. When factors are passed to these functions, the computation uses the underlying integer representation but from the documentation, it is supposed to work only on numeric types (integer, double, and complex).
>   ...	 Numeric arguments of type integer, double complex.

> Return the sum, product or mean of all numeric arguments. The value returned will be of the type of the highest argument types (integer < double < complex).

An example:

    iris2 <- iris[, 4:5]          # contains one numeric and one factor variables
    sapply(iris2, class)   
	# Petal.Width     Species 
	#   "numeric"    "factor"   

	cbind(
	  iris2,
	  Species_int= unclass(iris2$Species),
	  psum = psum(iris2$Petal.Width, iris2$Species),  
	  pmean = pmean(iris2$Petal.Width, iris2$Species),
	  pprod = pprod(iris2$Petal.Width, iris2$Species)
	)

	#     Petal.Width    Species Species_int psum pmean pprod
	# 1           0.2     setosa           1  1.2  0.60   0.2
	# 2           0.2     setosa           1  1.2  0.60   0.2
	# 3           0.2     setosa           1  1.2  0.60   0.2
	# 4           0.2     setosa           1  1.2  0.60   0.2
	# 5           0.2     setosa           1  1.2  0.60   0.2
	# 6           0.4     setosa           1  1.4  0.70   0.4
	# 7           0.3     setosa           1  1.3  0.65   0.3
	# 8           0.2     setosa           1  1.2  0.60   0.2
	# 9           0.2     setosa           1  1.2  0.60   0.2
	# ...

Output sessionInfo()

	> sessionInfo()
	R version 4.0.2 (2020-06-22)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows 10 x64 (build 19041)

	Matrix products: default

	locale:
	[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
	[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
	[5] LC_TIME=English_United States.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	other attached packages:
	[1] kit_0.0.6

	loaded via a namespace (and not attached):
	[1] compiler_4.0.2 tools_4.0.2 

P.S. I would like to know if you are planning to add an additional argument to these functions that allow to support list/data.frames. Something like `psum(..., l, na.rm=FALSE)` where `l` is a data.frame or more generally a list of numeric variables of equal lengths.; or alternatively where `...` also support a single data.frame or list(of equal-length numeric variables). 
If you have no plan, then could I open a request for this feature?

**Comment by 2005m** [comment]
Hi, thank you for your message. When I wrote these function, I was not really sure how to deal with factor, but given that `pmax` and `pmin` work on factors, I decided to let `psum` and Co work on factors as well. After all, the type of a factor is an integer so it is inline with the documentation, but maybe we should add a warning like `pmin` does because indeed that type of operation is not meaningful for factor.

With regards to your feature request, did you try version 0.0.6 of kit or the dev version? It should allow you to do something like that: `psum(iris[,1:3],na.rm=TRUE)`

Please let me know if any issue. Thank you

**Comment by 2005m** [comment]
`psum` and co will now result in error if used with factors. Closing for now. Let me know if any issue. Tks

**Comment by Kamgang-B** [comment]
Hi, sorry for my late reply. I updated `kit` package and these functions work on data.frame now. Nice to know that they now through an error on factors. This will start working from the next release (I think). 
I tried to get the link to the dev version but unfortunately, I did not find it. Am I missing something?
Thanks!

**Comment by 2005m** [comment]
For the dev version you need to install the github version. You will have to build it yourself using rtools (given that you are working on windows). Look online, you will find a lot of resources. Here is a link that can help 
[https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html](https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html) 

[https://github.com/r-lib/remotes](https://github.com/r-lib/remotes)
, but I usually just do a git clone, use `R CMD build` to build the package  and then install ...all from command line

[https://kbroman.org/pkg_primer/pages/build.html](https://kbroman.org/pkg_primer/pages/build.html)

The next release will probably appear on CRAN this weekend or the next.

**Comment by Kamgang-B** [comment]
Thank you for the very useful resources/links. I will try to install the dev version on my own. If I do not succeed, I will wait for the next release.
