### ISSUE TITLE
psum etc support lists. 

### ISSUE THREAD

**Issue by SebKrantz** [2005m/kit#20]
Hi Morgan, just a minor suggestion, it seems to me a bit restrictive to allow data frames but not lists as input to `psum` etc., e.g. `psum(mtcars)` works but `psum(unclass(mtcars))` does not. I also wanted to suggest defining the function as

```
psum <- function (..., na.rm = FALSE)  .Call(CpsumR, na.rm, if (...length() == 1L && is.list(..1)) ..1 else list(...))
```
See `help("...")`.

**Comment by 2005m** [comment]
Thanks Seb. I pushed your suggestions.
Did not do too much testing,  as I don't have much time.
