### ISSUE TITLE
Binaries through r-universe

### ISSUE THREAD

**Issue by SebKrantz** [2005m/kit#25]
In case this is of interest, I have set up a [fastverse r-universe](https://fastverse.r-universe.dev/) that builds binary versions of the GitHub version of your package for MAC and windows (new binaries are build within an hour of a new commit to your repo). Users can install these binaries using 

```
install.packages('kit', repo = 'https://fastverse.r-universe.dev')
```

You can also add a Badge to your README.md:
[![kit status badge](https://fastverse.r-universe.dev/badges/kit)](https://fastverse.r-universe.dev)

**Comment by 2005m** [comment]
Thank you. I will add the badge.
