### ISSUE TITLE
OpenMP disabled on OSX builds

### ISSUE THREAD

**Issue by mfansler** [2005m/kit#26]
Building from source, as well as installing binaries from CRAN fail to use OpenMP on OSX (x86_64).

Installing R 4.2.0 and kit, and loading shows:

```r
> install.packages('kit')
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/kit_0.0.11.tgz'
Content type 'application/x-gzip' length 243125 bytes (237 KB)
==================================================
downloaded 237 KB


The downloaded binary packages are in
	/var/folders/w8/nk968ztx0t57drmyw557kl480000gn/T//RtmpvQAvg1/downloaded_packages
> library(kit)
Attaching kit 0.0.11 (OPENMP disabled using 1 thread)
```

One can also observe [in the CRAN logs](https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/kit-00check.html) that there is a diff in the tests indicating that it is building without OpenMP:

>  ```
> checking tests ... [5s/5s] OK
>   Running ‘test_kit.R’ [4s/5s]
>   Comparing ‘test_kit.Rout’ to ‘test_kit.Rout.save’ ...39c39
>  < Attaching kit 0.0.11 (OPENMP disabled using 1 thread)
>  ---
> > Attaching kit 0.0.11 (OPENMP enabled using 1 thread)
> ```

Hitting a related issue trying to build for Conda Forge: https://github.com/conda-forge/staged-recipes/pull/17458

**Comment by 2005m** [comment]
Hi,
Openmp does not come by default on macos. You will need to install it. I think CRAN does not have it setup for mac either. When installing kit, the "installer" (it is actually done in the configuration file) will check whether you have openmp or not and pass the appropriate compiler flags to build the package.

Please see the following link:
https://mac.r-project.org/openmp/

Try to install any other package that uses openmp and you see that you will face the same issue. Most package will not warn you that openmp is disable they will just run on one thread.

I use a mac and have installed openmp ages ago.
Google that issue, you will probably find links that can help you resolve that issue. Here is a link that might help you.
https://firas.io/post/data.table_openmp/

**Comment by mfansler** [comment]
Okay, thanks for the references and sorry for the bother. I was confused by an older version (v0.0.7) that showed "*OPENMP enabled using 1 thread*" on OSX, so I thought that perhaps something was amiss with the `configure` script in newer versions. Honestly, my main concern is with building on the Conda Forge infrastructure where the `configure` script doesn't seem to automatically acknowledge the `llvm-openmp`, but I'll just keep troubleshooting that some more.
