### ISSUE TITLE
Introduce `panyNA`, `pallNA`, `panyv` and `pallv`?

### ISSUE THREAD

**Issue by SebKrantz** [2005m/kit#27]
Hi Morgan, I think `panyNA` and `pallNA` would be nice additions, especially `pallNA`, because it is a bit tedious to compare the number of row-wise missing values to the length of the data. Suggested implementations: 

```
panyNA  = function(...) as.logical(pcountNA(...))

pallNA  = function(...) {
   # unclass(..1) because if X is a data.frame, length() is more expensive 
   X <- if (...length() == 1L && is.list(..1)) unclass(..1) else list(...) 
   .Call(CpcountNAR, X) == length(X) 
}
```
Similarly you could create `panyv` and `pallv` for other values to be checked in parallel. This would integrate nicely with `collapse`where I have introduced `whichv()`, `anyv()` and `allv()` (in addition to `whichNA()`, and `allNA()`) to avoid the overhead of `==`.  Thanks for considering.

**Comment by 2005m** [comment]
Hi Seb, I have added the functions in a pull request and I can merge it so you can start using them.
I am not sure about panyv and pallv. Can you give me an example of how you want to use them?
I don't have much time to look into that. Also my computer died on me, so I doing all this from my phone. 
I will add test and review them in more details when I have time.
thank you

**Comment by SebKrantz** [comment]
Hi Morgan,

thanks a lot! Regarding the (v) versions, they would just generalize the
functionality to arbitrary values apart from NA. To be honest I don’t have
many concrete usage examples. One application would be to remove rows that
are all 0 or infinite. this can happen for example when differencing time-series data.
I once smoothed time series using a rolling median and then differenced the
data, which resulted in quite some all-0 rows, because many adjacent
intervals had the same median. I removed those for estimation which could
be done more easily using data %>% subset(!pallv(., value = 0)). But for
sure the NA case is the most common. Its up to you to add them or
not. I agree that they make more sense in the non-parallel setup where I
have introduced them, i.e. optimizing all(x == value) with allv(x, value).

Best,

Sebastian

**Comment by 2005m** [comment]
Hi Seb, i have added the 2 remaining functions. They should work. Let me know what you think.If ok for you, I will merge it asap so it is directly available in master. I will add test, example, news...etc later when I have more time. Thanks

**Comment by SebKrantz** [comment]
Hi Morgan,

thanks, looks good. Just note that in my testing as.logical() is more
efficient than > 0, so perhaps also use that for panyv(). I think these
functions are useful additions, especially for removing rows with
incomplete or all missing cases. Will be cool to benchmark panyNA() against
complete.cases(). So thanks again for implementing.

Best,

Sebastian
