### ISSUE TITLE
Feature request: pfirst and plast - skipping missing values in a row. 

### ISSUE THREAD

**Issue by SebKrantz** [2005m/kit#30]
Hi Morgan, first, consider my PR to avoid the warnings on CRAN. C-code is now compiled with stricter standards and many packages have to adjust. 

Then, I wondered, it would be nice to have something like parallel first and last value that select the first/last non-missing element of a row in a data frame. I have recently come across this working with Open Street Map where objects are classified by a number of different tags (character valued), and I wanted to create a single column classifying an object based on the availability of certain tags. That resulted in pretty long `nif()` statement e.g. `nif(!is.na(tag1), tag1, !is.na(tag2), tag2, ...)`, which would be simplified through something like `pfirst(tag1, tag2, tag3...)` or `pfirst(tags_df)`. 

I also came across another recent application where I wanted to assemble bilateral FDI data from different sources: OECD, Eurostat and IMF CDIS. I preferred the OECD over Eurostat over IMF data, which had the greatest coverage, so that also resulted in a `nif()` type statement to combine data from different sources based on the availability. 

So I believe there would be many potential use cases for some `pfirst()` and `plast()` functions - basically everything where you need to combine data from different columns based on availability.

**Comment by 2005m** [comment]
Hi Sebastian, hope you are well. I don't have much time to add new features to this package right now. Maybe in the future when I am a bit free. Thank you for the PR. I will try to push a new version of the package when I find a computer.

**Comment by SebKrantz** [comment]
Hi Morgan, I understand. A question in this regard: I could also implement
this through a PR, or you could make me a contributor to the repo or
transfer the repo to the fastverse organization (and become part of the
organization). Having neither a computer no time to develop the package
does not seem to be the best situation, and I do think kit fills an
important niche in the fastverse suite of packages and would benefit from
further development. I fully understand it though if you want to remain the
sole contributor to the package.

**Comment by 2005m** [comment]
Hi, I have added you as contributor. Thank you

**Comment by SebKrantz** [comment]
Thanks a lot! I've already implemented them, but will add some testing still. I guess you will still have to send it to CRAN though as you are the maintainer. I can send you a source package though once I'm done. Have you gotten any messages from them to react on the warnings? From my side I think I'll be ready with the testing and source package for kit 0.0.13 end of the week.

**Comment by 2005m** [comment]
Hi, I did not receive a message or email from CRAN regarding the warnings. The next CRAN version will be 0.0.12. I also have to add tests for some functions. I will try to do that from my phone if I can! Will try to see if I can find a laptop this weekend and push a new version to CRAN. Thank you.

**Comment by SebKrantz** [comment]
So I've added some further improvements: 

-  psum, pprod and pmean support logical inputs, in line with sum, prod and mean. logical data is just integers of 0 and 1 as you know, so I didn't really need to add extra code as all integer code works on logical data. 
- pcountNA (and therefore pallNA, panyNA) also support counting NULL or empty elements in list-vectors passed. This is very convenient in my opinion for things like sf data frames etc., and in-line with fnobs() in collapse. 

I have two remarks on the implementations of those parallel functions: 

- pprod returns an integer when when passed a list of integers. This is not in line with base::prod which always returns doubles, and also risky as integer overflows are very likely to occur with products. My suggestion here would be to come in line with base R and only output doubles (or complex). 
- You use coerceVector() to coerce integers to doubles if arguments have multiple types. This is an unnecessary inefficiency as math with integers and doubles is not a problem as far as I am aware (I do it in collapse and have never received an issue because of it). One would just have to create appropriate pointers. 

I guess the second one is not so relevant as it's more about optimization. I would, with your permission, implement the first remark to make sure we are on the safe side while the package still enjoys moderate use (which I think is going to change).

**Comment by SebKrantz** [comment]
If you are content please merge or tell me to merge, so we don't incur further conflicts. I adjusted the PR to keep the date (29.10) and version (0.0.12) you set.

**Comment by SebKrantz** [comment]
Hi Morgan, thanks for releasing to CRAN, but I suppose my changes to pprod() yesterday evening did not make it to CRAN anymore? (at least I don't see it in the NEWS). So should I then bump up the version to 0.0.13 and do a GitHub release to make it clear that the version 0.0.12 on GitHub and R-universe is different from CRAN?

**Comment by 2005m** [comment]
Hi, no pprod did not make to CRAN, it will be for the next release. Yes you can bump to 0.0.13 but please do it in a PR and let me merge cause it is difficult to keep track of the chqnges for me otherwise. I also need to tidy up the test files cause it is not passing in a clean way anymore. Thank you.

**Comment by 2005m** [comment]
No need to bump or fix the tests...I just did it

**Comment by SebKrantz** [comment]
Cool, thanks! and sorry for just merging. I'll stick to PR's in the future.

**Comment by 2005m** [comment]
No worries, not a big deal, it is just easier to track the changes ...

**Comment by SebKrantz** [comment]
> Hi Morgan, thanks for releasing to CRAN, but I suppose my changes to pprod() yesterday evening did not make it to CRAN anymore? (at least I don't see it in the NEWS). So should I then bump up the version to 0.0.13 and do a GitHub release to make it clear that the version 0.0.12 on GitHub and R-universe is different from CRAN?

Hi Morgan, I hope you are doing well! If you are not currently planning further changes, it would be good to see 0.0.13 on CRAN.

**Comment by 2005m** [comment]
Hi, Hope you are doing well too. 0.0.13 is on its way to CRAN.

**Comment by SebKrantz** [comment]
Great, thanks a lot! Yeah I’m good.
