### ISSUE TITLE
configure should check for compiler on Darwin, not force Clang-only flag with GCC

### ISSUE THREAD

**Issue by barracuda156** [2005m/kit#36]
This code breaks the build with GCC:
```
  if [ "`uname`" = "Darwin" ] ;then
    echo "*** On Darwin and OpenMP supported!"
    sed -e "s|@openmp_cflags@|-Xpreprocessor -fopenmp|g; s|@openmp_libslags@|-lomp|g; s|@realtime_libslags@||g;" src/Makevars.in > src/Makevars
  else
```
Correct flag would be just `-fopenmp` (no need to link `libgomp` explicitly). That is, `-lomp` should be added only when Clang is used.

**Comment by barracuda156** [comment]
UPD. Hmm, looks like it wants explicit linking: parhaps GCC flags are blocked or discarded:
```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘kit’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-kit/R-kit/work/kit-0.0.13/kit.Rcheck/00LOCK-kit/00new/kit/libs/kit.so':
  dlopen(/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-kit/R-kit/work/kit-0.0.13/kit.Rcheck/00LOCK-kit/00new/kit/libs/kit.so, 6): Symbol not found: _GOMP_parallel
  Referenced from: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-kit/R-kit/work/kit-0.0.13/kit.Rcheck/00LOCK-kit/00new/kit/libs/kit.so
  Expected in: dynamic lookup

Error: loading failed
```

**Comment by barracuda156** [comment]
Yeah, with `-lgomp` it builds fine and tests pass:
```
* checking tests ...
  Running ‘test_kit.R’
  Comparing ‘test_kit.Rout’ to ‘test_kit.Rout.save’ ... OK
 OK
```

**Comment by 2005m** [comment]
Hi, thanks for reporting. I don't have the hardware to test or solve this issue but happy to accomodate how much as I can and as long as it does not break any build on CRAN.
@souzapd, would you mind testing the solution of @barracuda156 and see if it breaks anything on your side? We recently solved an issue related to the above topic. Thank you.

**Comment by barracuda156** [comment]
@2005m I am just not sure how to test for compiler in configure. `libomp` is a LLVM library, GCC has `libgomp`, flags should be used accordingly; the bug was not noticed perhaps simply because not many people use GCC on macOS (or not reported).

This is what I had to do in the portfile for `kit` to make it build correctly both with GCC and Clang:
```
post-patch {
    if {[string match *gcc* ${configure.compiler}]} {
        reinplace "s,-lomp,-lgomp,g" ${worksrcpath}/configure
    } elseif {[string match *clang* ${configure.compiler}]} {
        reinplace "s,-Xpreprocessor -fopenmp,-Xpreprocessor -I${prefix}/include/libomp -fopenmp," ${worksrcpath}/configure
        reinplace "s,-lomp,-L${prefix}/lib/libomp -lomp,g" ${worksrcpath}/configure
    }
}
```

P. S. There is another package, `mixl`, that tests for OpenMP support; their test is wrong, but at least it does not break the build (it simply fails to recognize OpenMP support with GCC).

**Comment by 2005m** [comment]
You are probably right, it is just that I don't want to solve an issue and create another one for someone else, especially when I have no mean to check, test or verify that everything works fine. I will try to find out if there is a way to find out which compiler is used.

**Comment by souzapd** [comment]
Greetings.

@2005m on macOS, builds use `clang`, for which `gcc` and `g++` are just aliases. Running any of these in terminal with the `--version` flags displays the following

```shell
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 

@barracuda156 from your dump I see you are using macports. I also see a `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts` path. Are you running Snow Leopard? Would you mind sharing a bit more about the environment and setup you are using?

**Comment by souzapd** [comment]
Greetings.

@2005m on macOS, builds use Command Line Tools `clang`, for which `gcc` and `g++` are just aliases. Running any of these in terminal with the `--version` flag displays the following:

```shell
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 

@barracuda156 from your dump I see you are using macports. I also see a `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts` path. Are you running Snow Leopard? Would you mind sharing a bit more about the environment and setup you are using?

**Comment by souzapd** [comment]
Greetings.

@2005m I could try adjusting my setup to use `gcc` and see if it builds—my current setup to build `kit` is also the same used to build `data.table` (aka Homebrew to install `llvm/clang` and `libomp` with a custom Makevars file).

@barracuda156 
- Are you able to install `data.table` with OpenMP support? If not, their wiki has some [pointers on how to setup the environment](https://github.com/Rdatatable/data.table/wiki/Installation).
- Also, from your dump I see you are using macports. I also see a `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts` path. Are you running Snow Leopard on a PowerPC? Do you mind sharing more information on this?

**Comment by barracuda156** [comment]
> You are probably right, it is just that I don't want to solve an issue and create another one for someone else, especially when I have no mean to check, test or verify that everything works fine. I will try to find out if there is a way to find out which compiler is used.

@2005m Thank you for responding. As for GCC, I can refer to official documentation: https://gcc.gnu.org/onlinedocs/libgomp/Enabling-OpenMP.html
I.e., it is not something obscure or works-for-me :)

(That being said, _for me_ I actually had to explicitly pass `-lgomp`; however, I suspect it happened because configure script sterilizes flags which GCC normally passes automatically. I mean, I have written dozens of portfiles for software that uses OpenMP, and my testing environment is GCC – I know very well how it behaves, not only in theory.)

I do get your point about testing and certainly support that. But maybe someone trustable can test for you, if you have no suitable environment?

**Comment by barracuda156** [comment]
>  I could try adjusting my setup to use `gcc` and see if it builds—my current setup to build `kit` is also the same used to build `data.table` (aka Homebrew to install `llvm/clang` and `libomp` with a custom Makevars file).

@souzapd For w/e it’s worth, on macOS clang is the default compiler – though in Macports it is LLVM clang now, for `R` builds on Intel and ARM (because Apple clang does not support OpenMP, and we need a single compiler for `R` env).
Personally I find this odd/suboptimal – since `R` extensively uses Fortran, and not LLVM `flang` or `lfortran`, but `gfortran`, GCC would be logical choice. Besides, it also behaves more stable with regard to OpenMP.

Building `R` with GCC on recent macOS will _probably_ need some manual adjustments. Like, switching to X11 instead of native graphics and setting `libstdc++` instead of `libc++`. These are guesses, I had no time to test that.
On 10.6.8 (i386, x86_64, ppc32) everything works perfectly with GCC – without LLVM and clang.

> * Are you able to install `data.table` with OpenMP support? If not, their wiki has some [pointers on how to setup the environment](https://github.com/Rdatatable/data.table/wiki/Installation).

I will try and update you. I think I did not need to fix OpenMP there, so at least configure was sane enough.

> * Also, from your dump I see you are using macports. I also see a `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts` path. Are you running Snow Leopard on a PowerPC? Do you mind sharing more information on this?

Yeah, I have 10.6 PPC (10A190, a developer build) as my main system on G5 PowerMacs, and I use 10.6.8 Rosetta for testing along with that (on Intel). So both are powerpc-apple-darwin10, though 10A190’s SDK is somewhat in-between 10.5 and 10.6: some features were not yet implemented by the time of the build (like, GCD is not there, unwinding symbols are in libgcc and not libSystemB etc.).

P. S. So far with regard to `R` and packages I have not seen any practical differences between 10A190 and 10.6.8 Rosetta. (Well, I can recall a horrible configure script of `RcppParallel`, which fails on both, though differently, however same patch fixes both.)

**Comment by barracuda156** [comment]
@souzapd Well, as the source code of `data.table` itself, ironically, notices, it does nothing about the result of the test:
```
# First, try R CMD SHLIB to see if R can already compile
# things using OpenMP without any extra help from data.table
"${R_HOME}/bin/R" CMD SHLIB test-omp.c >/dev/null 2>&1 || R_NO_OPENMP=1

if [ "$R_NO_OPENMP" = "1" ]; then
  # Compilation failed -- try forcing -fopenmp instead.
  # TODO: doesn't R_NO_OPENMP need to be set to 0 before next line?
  ${CC} ${CFLAGS} -fopenmp test-omp.c || R_NO_OPENMP=1
  # TODO: and then nothing seems to be done with this outcome
else
  echo "R CMD SHLIB supports OpenMP without any extra hint"
fi
```

OpenMP support is recognized with GCC:
```
* installing *source* package ‘data.table’ ...
** using staged installation
zlib 1.2.13 is available ok
R CMD SHLIB supports OpenMP without any extra hint
** libs
```
But then nothing is done, no flags passed:
```
/opt/local/bin/gcc-mp-12 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc  -c assign.c -o assign.o
. . .
/opt/local/bin/gcc-mp-12 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch ppc -o data.table.so assign.o between.o bmerge.o chmatch.o cj.o coalesce.o dogroups.o fastmean.o fcast.o fifelse.o fmelt.o forder.o frank.o fread.o freadR.o froll.o frollR.o frolladaptive.o fsort.o fwrite.o fwriteR.o gsumm.o ijoin.o init.o inrange.o nafill.o nqrecreateindices.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o snprintf.o subset.o transpose.o types.o uniqlist.o utils.o vecseq.o wrappers.o -lz -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
PKG_CFLAGS =
PKG_LIBS = -lz
```
Expectedly, no linking for dylib:
```
svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/data.table/libs/data_table.so
/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/data.table/libs/data_table.so:
	data_table.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.7)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib (compatibility version 4.2.0, current version 4.2.2)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```

This is not a bug of GCC though, but a bug of `data.table`.

UPD. By the way, I cannot see how it possibly would link to `libomp` with Clang. `SHLIB_OPENMP_CFLAGS` is not defined, so reinplace gonna be empty.

**Comment by barracuda156** [comment]
@souzapd However if we fix a broken code in `data.table`, then yes, it links to `libgomp` with just `-fopenmp` flag passed:
```
/opt/local/bin/gcc-mp-12 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch ppc -o data.table.so assign.o between.o bmerge.o chmatch.o cj.o coalesce.o dogroups.o fastmean.o fcast.o fifelse.o fmelt.o forder.o frank.o fread.o freadR.o froll.o frollR.o frolladaptive.o fsort.o fwrite.o fwriteR.o gsumm.o ijoin.o init.o inrange.o nafill.o nqrecreateindices.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o snprintf.o subset.o transpose.o types.o uniqlist.o utils.o vecseq.o wrappers.o -fopenmp -lz -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
PKG_CFLAGS = -fopenmp
PKG_LIBS = -fopenmp -lz
```
All good now:
```
svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/data.table/libs/data_table.so
/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/data.table/libs/data_table.so:
	data_table.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.7)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib (compatibility version 4.2.0, current version 4.2.2)
	/opt/local/lib/libgcc/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```

UPD. Okay, I admittedly skipped reading wiki-link above, now I did, and there are instructions, though only clang-specific (and arguably rather overwhelming for a user of R and not a developer).
So anyway, answering your question: _yes, linking to `libgomp` works with GCC._

**Comment by 2005m** [comment]
@barracuda156 , could you please clarify:
- which changes in the configure file would work for you? i.e. which flag to add / remove for the package to install on your system?
- could you tell me what you get when type in the terminal `gcc --version | sed -n '1p' | cut -d' ' -f1`? @souzapd can you please also run this command on your side?

Thank you

**Comment by barracuda156** [comment]
> * which changes in the configure file would work for you? i.e. which flag to add / remove for the package to install on your system?

I would keep changes to the minimum needed to unbreak the build. So use `-fopenmp` with any compiler, but add `-lomp` only when Clang is used.
If that is problematic to implement, then having OpenMP disabled as a fallback is preferable to forcing flags that break the build for anyone using GCC.

That is, logic as follows:
1) test for `-fopenmp` support; 2) if no, disable OpenMP, if yes, 3) test for compiler (clang/gcc) or libcxx (libc++/libstdc++), if clang detected, add also `-lomp`.
If that is overkill, then just pass `-fopenmp` and add README akin to what is done for `data.table`, advising to use `libomp` with Clang (GCC is good as it is, no extra components needed).

Since both clang and gcc can be used on Darwin and/or on x86_64, neither arch nor platform can be used to infer which ldflags to pass in discussed case.

> * could you tell me what you get when type in the terminal `gcc --version | sed -n '1p' | cut -d' ' -f1`? @souzapd can you please also run this command on your side?

Literal answer would be `powerpc-apple-darwin10-gcc-4.2.1`, but it is irrelevant, since I (and Macports) do not use system compilers for `R` and R packages. I use GCC 12.2.0 (`gcc-mp-12`), Macports is still stuck at GCC 7.5.0 for older macOS. (Occasionally this creates problems when some build system forces literal `gcc`, which pulls system compiler, but that can be fixed by patching.) We do not need to consider gcc-4.2 at all, on any system, since it is incapable of building even R itself.

**Comment by 2005m** [comment]
I am confused by your answer, probably because I have never used a powerpc and don't really know what macport is. 
What I am trying to do is detect which compiler you are using. The issue is that I am confused by what the command I gave you returns and on the other side by you telling me that you use GCC 12.2. I am not sure how I can detect which compiler you are using in these conditions?

**Comment by barracuda156** [comment]
@2005m Ah, got it. Well, we do not need a version of GCC here. _Any_ GCC being used will support OpenMP. Any test that allows to differentiate between some GCC vs some Clang will do.

(PowerPC is irrelevant here, there is nothing arch-specific. It is just on PowerPC we have only GCC, so any related bug becomes obvious. But everything said above equally applies to GCC on x86_64.)

**Comment by 2005m** [comment]
Ok thanks. I am walking in the dark so I will need your help.
Can you try the following configure file for me and see if it works?

```bash
#!/bin/sh
CC=`${R_HOME}/bin/R CMD config CC`
CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`

printf "#include <omp.h>\nint main () { return omp_get_num_threads(); }" | ${CC} ${CFLAGS} -fopenmp -xc ->/dev/null 2>&1 || R_NO_OPENMP=1;
rm a.out >/dev/null 2>&1

if [ "$R_NO_OPENMP" = "1" ]; then
  printf "#include <omp.h>\nint main () { return omp_get_num_threads(); }" | ${CC} ${CFLAGS} -Xpreprocessor -fopenmp -lomp -xc ->/dev/null 2>&1 || R_NO_OPENMP=2;
  rm a.out >/dev/null 2>&1
  if [ "$R_NO_OPENMP" = "2" ]; then
    if [ "`uname`" = "Linux" ] ;then
      echo "*** On Linux and OpenMP not supported!"
      sed -e "s|@openmp_cflags@||g; s|@openmp_libslags@||g; s|@realtime_libslags@|-lrt|g;" src/Makevars.in > src/Makevars
    else
      echo "*** Not on Linux and OpenMP not supported!"
      sed -e "s|@openmp_cflags@||g; s|@openmp_libslags@||g; s|@realtime_libslags@||g;" src/Makevars.in > src/Makevars
    fi
  else
    echo "*** OpenMP supported (-Xpreprocessor)!"
    sed -e "s|@openmp_cflags@|-Xpreprocessor -fopenmp|g; s|@openmp_libslags@|-lomp|g; s|@realtime_libslags@||g;" src/Makevars.in > src/Makevars
  fi
else
  if [ "`uname`" = "Darwin" ] ;then
    if gcc --version | grep -i "gcc" > /dev/null; then
      echo "*** On Darwin and GCC OpenMP supported!"
      sed -e "s|@openmp_cflags@|-Xpreprocessor -fopenmp|g; s|@openmp_libslags@|-lgomp|g; s|@realtime_libslags@||g;" src/Makevars.in > src/Makevars
    elif clang --version | grep -i "clang" > /dev/null; then
      echo "*** On Darwin and Clang OpenMP supported!"
      sed -e "s|@openmp_cflags@|-Xpreprocessor -fopenmp|g; s|@openmp_libslags@|-lomp|g; s|@realtime_libslags@||g;" src/Makevars.in > src/Makevars
    fi
  else
    echo "*** On Linux and OpenMP supported!"
    sed -e "s|@openmp_cflags@|\$(SHLIB_OPENMP_CFLAGS)|g; s|@openmp_libslags@|\$(SHLIB_OPENMP_CFLAGS)|g; s|@realtime_libslags@|-lrt|g;" src/Makevars.in > src/Makevars
  fi
fi

exit 0
```

**Comment by souzapd** [comment]
Hi, @2005m.

> * could you tell me what you get when type in the terminal `gcc --version | sed -n '1p' | cut -d' ' -f1`? @souzapd can you please also run this command on your side?

That just outputs `Apple` on my machine.

---- 

What has got me is that OP is running an unsupported Mac OS X version (Snow Leopard) on unsupported hardware (Power PC). As the developer of the library, I think it is under your purview to support such setups or not (I know many don't, e.g. Homebrew itself).

An aggravating item regarding this issue is concerns the `data.table` wiki: it has instructions for Macport users using gcc under a subsection titled _Variant for Macports users_. The verbose style used by OP and its disjointed lecturing is making it hard for me to follow through.

@2005m If you decide to implement the makevars fix, let me know so I can test it.

**Comment by 2005m** [comment]
@souzapd , thank you, i won't go ahead with a fix if it is breaking something else. May I please ask you to check whether the above `configure` file works for you? Please also test that you have full openmp support and that the tests are passing. Thank you

**Comment by souzapd** [comment]
@2005m I've just finished testing. Loading the library returns `Attaching kit 0.0.13 (OPENMP enabled using 1 thread)`, and the tests are ok when running `R CMD check`.

**Comment by barracuda156** [comment]
> What has got me is that OP is running an unsupported Mac OS X version (Snow Leopard) on unsupported hardware (Power PC). As the developer of the library, I think it is under your purview to support such setups or not (I know many don't, e.g. Homebrew itself).

As I have mentioned above, the problem has nothing to do with either arch or OS.

**Comment by barracuda156** [comment]
It certainly has improved with the new configure update: compiler detection is working and OpenMP flag is passed.
I got a load failure, like originally when I used `-fopenmp` by patching configure, but this is a trivial error (we can handle this in Macports):
```
Error: package or namespace load failed for ‘kit’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_R_R-kit/R-kit/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-kit-0.0.13/00new/kit/libs/kit.so':
  dlopen(/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_R_R-kit/R-kit/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-kit-0.0.13/00new/kit/libs/kit.so, 6): Symbol not found: _GOMP_parallel
  Referenced from: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_R_R-kit/R-kit/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-kit-0.0.13/00new/kit/libs/kit.so
  Expected in: dynamic lookup

Error: loading failed
Execution halted
ERROR: loading failed
```

P. S. Passing `-lgomp` explicitly (for GCC case) in addition to `-fopenmp` fixes this, but at the moment I don’t know why it fails without.

**Comment by 2005m** [comment]
Hi, it seems to be failing because gcc is unable to link to openmp library properly. I can add -lgomp. Is that an issue for you? If so why?

**Comment by 2005m** [comment]
It makes sense that you have to pass -lgomp for openmp to work properly. How do you want it to work properly otherwise?
This might help: 
https://stackoverflow.com/questions/22938238/difference-between-linking-openmp-with-fopenmp-and-lgomp

**Comment by 2005m** [comment]
I have updated the configure file above.  Can you check again if it works and that all tests pass? Thanks.

**Comment by barracuda156** [comment]
> Hi, it seems to be failing because gcc is unable to link to openmp library properly. I can add -lgomp. Is that an issue for you? If so why?

It should not be needed (according to GCC documentation), and normally it is not (from experience), but here it is, for w/e reason; perhaps something prevents GCC from linking correctly.
I think it doesn’t hurt passing the flag explicitly indeed.

**Comment by barracuda156** [comment]
> I have updated the configure file above.  Can you check again if it works and that all tests pass? Thanks.

Thank you, I will test today and update you. (Been offline yesterday.)

**Comment by 2005m** [comment]
> It should not be needed (according to GCC documentation)

Do you have a link about that? Thanks

**Comment by barracuda156** [comment]
> > It should not be needed (according to GCC documentation)
> 
> Do you have a link about that? Thanks

Just above: https://github.com/2005m/kit/issues/36#issuecomment-1449231622
It was implemented back in 2005: https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=3fc6fee2064ca50c6124f08d77ef0d759a499558

**Comment by 2005m** [comment]
I think the reason of why gcc does not link properly is explained here:
https://binhbar.com/posts/2020/06/compiling-openmp-libraries-on-macos/

**Comment by barracuda156** [comment]
> I think the reason of why gcc does not link properly is explained here:
> https://binhbar.com/posts/2020/06/compiling-openmp-libraries-on-macos/

If that was the case, it would always require passing `-lgomp` explicitly, but it does not, as a matter of fact, not even with `R` packages in particular. But anyway, perhaps not really important why in this case we do need an extra flag, since adding it imposes no adverse consequences.

**Comment by 2005m** [comment]
From the post, my undersranding is that if you are on mac you <ins>sometimes</ins> have to pass `-lgomp` if you are using gcc because some symbols such as `_GOMP_parallel` because gcc will call Apple's linker which does not know about them. Hence I understand that `-lgomp` might not be needed in case where such symbols are not used.

If you are not on a mac, you shouldn't need at all the additional flag at all.

Unfortunately I don't have the hardware to test. It would nice if someone can prove that wrong as it would enable us to make progress.

Yes it seems that adding the flag doesn't hurt but we might be wrong as well here...

Let me if everything works fine with the above configure file. If it also works for @souzapd , I will do further testing on rhub to check that nothing is failing and then will push the changes.

**Comment by barracuda156** [comment]
@2005m I will do testing tonight. The day was busy.

**Comment by barracuda156** [comment]
@2005m Yes, it work perfectly now (with your latest update to configure). Flags are passed, linking is done:
```
36-137% otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/kit/libs/kit.so
/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/kit/libs/kit.so:
	kit.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.99)
	/opt/local/lib/libgcc/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 511.1.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib (compatibility version 4.2.0, current version 4.2.2)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```

**Comment by 2005m** [comment]
Tests as well? Please try with different number of threads. Thank you

**Comment by 2005m** [comment]
@souzapd , can you please check as well with the configure file above?
Thanks

**Comment by barracuda156** [comment]
@2005m Tests pass, no surprise here, since I have already done the same (passing needed flags), just via a patch, and tests were good.
```
--->  Configuring R-kit
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-kit/R-kit/work/kit-0.0.13" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes 
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘kit’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘kit_0.0.13.tar.gz’

--->  Building R-kit
--->  Testing R-kit
* using log directory ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-kit/R-kit/work/kit-0.0.13/kit.Rcheck’
* using R version 4.2.2 (2022-10-31)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* using session charset: UTF-8
* checking for file ‘kit/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘kit’ version ‘0.0.13’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘kit’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘test_kit.R’
  Comparing ‘test_kit.Rout’ to ‘test_kit.Rout.save’ ... OK
 OK
* checking PDF version of manual ... OK
* DONE

Status: OK
```

**Comment by 2005m** [comment]
@souzapd , you can check directly the master branch if you want. I have pushed everything there.

**Comment by barracuda156** [comment]
@2005m Thank you for working on this!

**Comment by souzapd** [comment]
@2005m good morning. Package installed and loaded successfully, `R CMD check` passes.

**Comment by 2005m** [comment]
Thank you guys.
