### ISSUE TITLE
`.onLoad` function clobbers previously set `kit.nThread` option

### ISSUE THREAD

**Issue by jpcirrus** [2005m/kit#39]
In `Rprofile`, amongst other config, I have:

```R
options(kit.nThread = 10L)
```

However, on attaching `kit`, in `R/call.R` the `.onLoad` function clobbers that by setting the value to `1L`, requiring it to be set again. Would it be possible to make that conditional on it not having previously been set?

**Comment by 2005m** [comment]
I just pushed some code on master. Could you please check whether it works for you please?
Thank you

**Comment by jpcirrus** [comment]
Thanks. That will work. The `.onAttach` function in  `R/call.R` would also need to replace `" using 1 thread)"))` with `" using", getOption("kit.nThread"), "thread)"))`,  or the plural `threads` if `kit.nThread > 1L`. And `tests/test_kit.Rout.save:56` would need changing to match.

**Comment by 2005m** [comment]
Thank you, I will look at it tomorrow. Lign 56 in Rout.save has been annoying me for quite some time. It does not always match on CRAN and it really depends on the configuration and setup of the machine. Not I can really fix that given that it is "hardcoded".

**Comment by 2005m** [comment]
Pushed a commit. Let me know if any issue. Thank you.

**Comment by jpcirrus** [comment]
Works great. Many thanks, much appreciated.
