### ISSUE TITLE
nswitch and co. 

### ISSUE THREAD

**Issue by SebKrantz** [2005m/kit#41]
Hi Morgan, 

I have encountered the following: 

``` r
library(kit)
#> Attaching kit 0.0.13 (OPENMP disabled using 1 thread)
nswitch(rep(1:4, each = 2), 1L, rnorm(8), 2L, rnorm(8), 3L, 0.344, 4L, 0.455)
#> [1] -0.59760479 -0.59760479  0.09574917  0.09574917  0.34400000  0.34400000
#> [7]  0.45500000  0.45500000
```

<sup>Created on 2024-04-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think `nswitch()` should work differently, it should take the corresponding values from the random normal vectors instead of just replicating the first element.

**Comment by gitboy16** [comment]
Hi Seb, please check master and let me know if it is fixed and as you expect it. Thank you.

**Comment by 2005m** [comment]
Hi Seb, please check the master branch. Let me know if the issue is fixed and it is as you expect it. Thank you.

**Comment by SebKrantz** [comment]
Thanks for the quick fix!
