### ISSUE TITLE
a nested version of vswitch, nswitch?

### ISSUE THREAD

**Issue by shrektan** [2005m/kit#5]
I find `vswitch` is quite useful to me. 

As you stated in the doc, it can be regarded as a special case of `nif()`. It means one of the main advantages besides speed is the conviniences.  I often find a nested version of `vswitch` (maybe we call it `nswitch`?) like below is useful. It's easier to read and write when the values / outputs are not small.

```r
nswitch(
   x,
  "a", 1,
  "b", 2,
  "c", 3,
  default = 4
)
```

However, I have to write it like this for now, due to the missing of such function / API.

```r
vswitch(x, c("a","b","c"), c(1,2,3), default = 4)
```

So I'm opening a FR here to see if we can have such nested version of vswitch or not.

Thanks!

**Comment by 2005m** [comment]
Don't have much time these days. But If I get a chance I will have a look before a November release. If not maybe for later.

**Comment by 2005m** [comment]
In case you have no feedback on the PR, I am planning to close this FR by the end of the week. thanks
